// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:habitt/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ScheduleTypeAdapter());
    registerAdapter(DayAdapter());
    registerAdapter(HabitAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(ScheduleTypeAdapter());
    registerAdapter(DayAdapter());
    registerAdapter(HabitAdapter());
  }
}
